version: '3'

networks:
  shorturl-network:
    driver: bridge
    ipam:
      driver: default

services:
  shorturl:
    container_name: shorturl
    image: shorturl
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    volumes:
      - './:/var/www/app'
      - '/var/www/app/node_modules'
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - "3030:3000"
    networks:
      - shorturl-network

  shorturl-db:
    container_name: shorturl-db
    image: postgres
    environment:
      POSTGRES_DB: shorturl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - shorturl-network

  shorturl-test-db:
    container_name: shorturl-test-db
    image: postgres
    environment:
      POSTGRES_DB: shorturl-test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - shorturl-network
